MONGODB_DB_NAME = "SEProject"
MONGODB_URL = "mongodb://localhost:27017/Users"
API_V1_STR = "/api/v1"
MAX_CONNECTIONS_COUNT = 10
MIN_CONNECTIONS_COUNT = 1
SECRET_KEY="QUIZ"
MAIL_PASS="evcutspgdtmqduyi"
SUBJECT='Aryabhatta'
ISS ='https://sangam.ai/'
